Repository Shoomec74/bot-kits-backend, pull requests merged in 2023-09, with the labels that each got.

#92 pull request: добавить авторизация через вконтакте
  .env.example
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/guards/index.ts
  src/auth/guards/vkontakte.guards.ts
  src/auth/strategies/index.ts
  src/auth/strategies/vkontakte.strategy.ts
Labels: enhancement

#94 pull request: добавить защиту маршрутов по ролям
  src/auth/decorators/roles.decorator.ts
  src/auth/guards/role.guard.ts
  src/platforms/platforms.controller.ts
  src/platforms/platforms.module.ts
Labels: enhancement

#104 refactor(auth): переделал авторизацию на Authorization Code Flow
  src/auth/auth.controller.ts
  src/auth/guards/index.ts
  src/auth/guards/yandex.guards.ts
  src/auth/strategies/index.ts
  src/auth/strategies/yandex.strategy.ts
  swagger.yaml
Labels: refactor

#96 Refacor/swagger auth
  package-lock.json
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dto/auth.dto.ts
  src/auth/dto/combined.dto.ts
  src/auth/dto/request-body.dto.ts
  src/auth/dto/response-body.dto.ts
  src/utils/apiPropertyFactory.ts
  swagger.yaml
Labels: refactor

#105 pull request: рефакторинг ответа сервера при регистрации\логине
  src/auth/auth.service.ts
  src/profiles/profiles.service.ts
Labels: refactor

#114 pull request: изменить форму ответа при регистрации/логине
  src/accounts/accounts.service.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/profiles/profiles.service.ts
Labels: bug, refactor

#115 pull request: добавить ручку для получения всех аккаунтов по id профиля
  src/profiles/profiles.controller.ts
  src/profiles/profiles.service.ts
Labels: enhancement
